# Generated by Django 4.2.4 on 2023-08-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendorid',
            field=models.CharField(default='', max_length=250),
        ),
    ]
