# Generated by Django 4.2.4 on 2023-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
