# Generated by Django 4.2.4 on 2023-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('paymentmethod', models.CharField(max_length=250)),
                ('transactionid', models.CharField(max_length=250)),
            ],
        ),
    ]
