# Generated by Django 4.2.4 on 2023-08-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.CharField(default='', max_length=250),
        ),
    ]
